<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Project Laminas')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript() ?>
</head>
<body>


<nav class="navbar navbar-expand-md navbar-dark bg-black mb-4" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="<?= $this->url('home') ?>">
            Allan<b class="text-success">.</b>R
            <!--            <img src="-->
            <?php //= $this->basePath('img/laminas-logo.svg') ?><!--" alt="Laminas">MVC Skeleton-->
        </a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
                <i class=" border-0 fa fa-bars"></i></span>
        </button>
        <div class="collapse navbar-collapse text-right" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link  border-0" href="<?= $this->url('home') ?>">Home <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <?= $this->content ?>
    <hr>

    <footer>
        <p>
            &copy; <?= date('Y') ?>
            <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
        </p>
    </footer>
</div>
<?= $this->inlineScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.5.1.min.js')) ?>
</body>
</html>
