<?php

$title = 'Meus albums';
$this->headTitle($title);
?>
<h1 class="text-muted" ><?= $this->escapeHtml($title) ?></h1>

<p class="d-flex justify-content-end container">
    <a class="btn btn-success" href="<?= $this->url('album', ['action' => 'create']) ?>">Adicionar Album</a>
</p>

<table class="table text-center">
    <tr>
        <th>Titulo</th>
        <th>Artista</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td>
                <a class="btn btn-success" href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Editar</a>
                <a class="btn btn-danger" href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
